# Generated by Django 2.0.6 on 2018-06-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security',
            field=models.CharField(choices=[('Whats your pet name', 'Whats your pet name'), ('Whats your best frens name', 'Whats your best frens name'), ('How old are you', 'How old are you')], default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
