# Generated by Django 2.0.6 on 2018-06-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180622_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='security',
        ),
        migrations.AddField(
            model_name='customuser',
            name='answer',
            field=models.CharField(blank=True, default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(choices=[('Whats your pet name', 'Whats your pet name'), ('BOOO', 'Whats your best frens name'), ('How old are you', 'How old are you')], default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=False, max_length=1),
        ),
    ]
