# Generated by Django 2.0.6 on 2018-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180622_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(choices=[('Whats your pet name', 'Whats your pet name'), ('Whats your best friends name', 'Whats your best frens name'), ('How old are you', 'How old are you')], max_length=200),
        ),
    ]
