# Generated by Django 2.0.6 on 2018-06-25 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180625_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 25, 10, 24, 43, 405476)),
        ),
    ]
