# Generated by Django 2.0.6 on 2018-06-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180625_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.CharField(choices=[('1', 'A'), ('2', '2'), ('3', '3')], max_length=200),
        ),
    ]
