# Generated by Django 2.0.6 on 2018-06-25 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180625_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bootstrap_date',
            field=models.DateField(default=datetime.date.today, verbose_name='bootstrap trial'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(choices=[('Whats your pet name', 'Whats your pets name'), ('Whats your best friends name', 'Whats your best frens name'), ('How old are you', 'How old are you')], max_length=200),
        ),
    ]
