# Generated by Django 2.0.6 on 2018-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_bootstrap_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resume',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
