# Generated by Django 2.0.6 on 2018-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_customuser_yearless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(choices=[('Whats your pet name', 'Whats your pets name'), ('Whats your best friends name', 'Whats your best frens name'), ('How old are you', 'How old are you')], default='Whats your pet name', max_length=200),
        ),
    ]
