# Generated by Django 2.0.6 on 2018-07-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180708_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(choices=[("Whats your pet's name", 'Whats your pets name'), ("Whats your best friend's name", "Whats your best friend's name"), ('What is your postal code', 'What is your postal code'), ('What is your first phone number', 'What is your first phone number'), ('Which is your favorite book', 'Which is your favorite book')], default="Whats your pet's name", max_length=200),
        ),
    ]
