# Generated by Django 2.0.6 on 2018-07-10 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180710_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(default='documents20180702/Event_list_UXMJVy4.pdf', upload_to='documents%Y%m%d')),
                ('birth_certificate', models.FileField(default='documents20180702/Event_list_UXMJVy4.pdf', upload_to='documents%Y%m%d')),
                ('marksheet', models.FileField(default='documents20180702/Event_list_UXMJVy4.pdf', upload_to='documents%Y%m%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
        migrations.AddField(
            model_name='documents',
            name='customuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
