# Generated by Django 2.0.6 on 2018-07-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180710_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
