# Generated by Django 2.0.6 on 2018-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='customuser',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='answer',
            field=models.CharField(help_text='<ul><li>Security Answer are case sensitive</li><li>They can be used to recover your password.</li></ul>', max_length=255),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
