# Generated by Django 2.0.6 on 2018-07-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180721_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
