# Generated by Django 2.0.6 on 2018-07-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
