# Generated by Django 2.0.6 on 2018-07-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180721_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
