# Generated by Django 2.0.6 on 2018-07-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180721_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='number',
            new_name='contact_number',
        ),
    ]
