# Generated by Django 2.0.6 on 2018-07-09 08:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180704_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
