# Generated by Django 2.0.6 on 2018-07-11 09:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='text2',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
