# Generated by Django 2.0.6 on 2018-07-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_leaveapplication_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='text2',
        ),
    ]
