# Generated by Django 2.0.6 on 2018-07-18 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_remove_leaveapplication_text2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='')),
                ('approval', models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='reasons',
            field=models.CharField(blank=True, choices=[('SICK LEAVE', 'SICK LEAVE'), ('PERSONAL LEAVE', 'PERSONAL LEAVE'), ('SABBATICAL LEAVE', 'SABBATICAL LEAVE'), ('MATERNITY LEAVE', 'MATERNITY LEAVE')], max_length=100),
        ),
    ]
