# Generated by Django 2.0.6 on 2018-07-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180721_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
    ]
